from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.domain.entities.agent import Agent
from app.domain.entities.assignment import Assignment
from app.domain.entities.location import Location
from app.domain.entities.user import User


class UserRepository(Protocol):
    async def create(self, user: User) -> User: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...


class AgentRepository(Protocol):
    async def create(self, agent: Agent) -> Agent: ...
    async def get_by_id(self, agent_id: UUID) -> Agent | None: ...
    async def update(self, agent: Agent) -> Agent: ...
    async def delete(self, agent_id: UUID) -> None: ...
    async def list(
        self, status: str | None = None, region: str | None = None
    ) -> list[Agent]: ...


class LocationRepository(Protocol):
    async def create(self, location: Location) -> Location: ...
    async def get_by_id(self, location_id: UUID) -> Location | None: ...
    async def update(self, location: Location) -> Location: ...
    async def delete(self, location_id: UUID) -> None: ...
    async def list(
        self, is_active: bool | None = None, city: str | None = None
    ) -> list[Location]: ...


class AssignmentRepository(Protocol):
    async def create(self, assignment: Assignment) -> Assignment: ...
    async def get_by_id(self, assignment_id: UUID) -> Assignment | None: ...
    async def update(self, assignment: Assignment) -> Assignment: ...
    async def list(
        self,
        agent_id: UUID | None = None,
        location_id: UUID | None = None,
        status: str | None = None,
    ) -> list[Assignment]: ...
